version: "3.3"
services:
    web:
        container_name: phpserver
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
        ports:
            - 8081:80
        links:
            - db
    db:
        container_name: mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: /br4vu5_root/is
            MYSQL_DATABASE: crud_vikings
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - 3306:3306
            
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        ports:
          - 8080:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306